import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import Navbar from '@/components/Navbar';

const fustat = localFont({
  src: './../../public/font/Fustat.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Drag and Drop - Hy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fustat.className} dark`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
